nodeCIDR: 10.200.0.0/24
debug: false

image:
  repository: ghcr.io/limrun-inc/limguard
  tag: latest
  pullSecrets: []

ipOverrides:
  - ip: 10.200.0.1
    node: eu-hel1-5-staging
  - ip: 10.200.0.2
    node: eu-staging-m22-dffc
